import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/header/page";
import Footer from "./component/layout/footer/page";
import BackToTopButton from "./component/backToTopButton/page";
import Loader from "./component/loader/loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Loader />
        {children}
        <Footer />
        <BackToTopButton />
      </body>
    </html>
  );
}
